### ISSUE TITLE
Add Tigase iOS app to the list

### ISSUE THREAD

**Issue by herbsmn** [bascht/omemo-top#111]
https://tigase.tech/issues/7511

**Comment by bascht** [comment]
@herbsmn Thanks for the hint! Do you want to submit a PR? We can assist if you need help to get started. :smile:

**Comment by Echolon** [comment]
@herbsmn I'm confused, aren't both clients in the list already?

**Comment by bascht** [comment]
@Echolon Jip indeed. Tigase was added via #157
