### ISSUE TITLE
Is Pidgin really 100%?

### ISSUE THREAD

**Issue by ilmaisin** [bascht/omemo-top#127]
Pidgin is categorized fully complete, but I don't think it really is. The [ticket](https://developer.pidgin.im/ticket/16801) still actually has the "new" status.

The OMEMO support is achieved by building and installing a third-party plugin that is labelled as "highly experimental" according to the [readme](https://github.com/gkdr/lurch#caveats). And to achieve the multi-device capability, an important selling point of OMEMO, you need to build and install another third-party plugin for Carbons. Even then the multi-device capability isn't quite complete, since there is no Message Archive Management available for Pidgin at all.

**Comment by bascht** [comment]
Interesting. I don't use Pidgin myself but it sounds like it's some serious effort to get OMEMO to work with it. Curious to see what the response to https://developer.pidgin.im/ticket/16801#comment:39 will be.

**Comment by bascht** [comment]
Thanks for the notice!
