### ISSUE TITLE
Should Monal really be on 80%?

### ISSUE THREAD

**Issue by moppman** [bascht/omemo-top#135]
I'm having high hopes on Monal, with ChatSecure giving my iOS friends quite a lot of headaches with notifications for omemo messages.
That said, the Monal Testflight betas don't have omemo implemented yet, so I find the 80% graph on omemo.top kind of misleading.

**Comment by bascht** [comment]
Yip, indeed, the progress bar is problematic, see also: #122 and #127.

**Comment by Echolon** [comment]
I think it is a question of 1-2 weeks till he will release it. But we can go back to 70% or so, as probably OMEMO Muc wont work as it is often the case for developments

**Comment by Echolon** [comment]
> Close
