### ISSUE TITLE
Converse Progress is wrong

### ISSUE THREAD

**Issue by NicoHood** [bascht/omemo-top#138]
Converse does not support OMEMO for group chats:
https://github.com/conversejs/converse.js/issues/497#issuecomment-443409922

This PR is wrong:
https://github.com/bascht/omemo-top/pull/121

**Comment by novalis111** [comment]
My last test worked fine. Problem is the room needs to be non-anonymous and members only, plus you need to validate every fingerprint of every user in the room. Bit of a hassle, but possible.

**Comment by bascht** [comment]
Given that @licaon-kter is a contributor to Converse.js this looks a bit odd, yes. 
I think we should reset the progress to something like ~75/80%

**Comment by licaon-kter** [comment]
I'm no contributor.

But...it kinda works, in my testing contacts get messages encrypted by the Converse user doesn't.

**Comment by moppman** [comment]
The progress bar for converse shouldn't be full anyway, though: Files are sent unencrypted even if omemo is activated, and aesgcm links aren't decrypted either.

**Comment by danjde** [comment]
I would like to tell you that version 4.2.0 does not support sending msg in OMEMO mode due a library problem: https://github.com/conversejs/converse.js/issues/1524

You can confirm the above from [Converse.js official page](https://conversejs.org/fullscreen.html)

**Comment by licaon-kter** [comment]
@danjde works for me, so I would generalize that issue.

**Comment by Echolon** [comment]
I think I can close this due to the fifth and sixth release of Converse.

Otherwise please create a simple reasonable PR.

Cheers guys!
