### ISSUE TITLE
Could you add Audium

### ISSUE THREAD

**Issue by jugendhacker** [bascht/omemo-top#160]
It seems to support OMEMO via Plugin but it isn't really stable es far as I can see

https://adium.im/

**Comment by bascht** [comment]
Hi @jugendhacker! Adium is already in our list: http://omemo.top/#Adium :-)

On 18 April 2019 18:08:16 CEST, jugendhacker <notifications@github.com> wrote:
>It seems to support OMEMO via Plugin but it isn't really stable es far
>as I can see
>
>https://adium.im/
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bascht/omemo-top/issues/160


Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jugendhacker** [comment]
Oh sorry didn't looked enough
