### ISSUE TITLE
Jitsi listing is confusing

### ISSUE THREAD

**Issue by wrooot** [bascht/omemo-top#166]
It is listed as Jitsi. I think it refers to older Jitsi desktop client? Then maybe it should be named as "Jitsi Desktop (Legacy)". With os_support: [Linux,macOS,Windows]. Link should point to https://desktop.jitsi.org/ I can do a PR. Just wanted to discuss this first.

Because Jitsi is more as an organization now. They have Jitsi Meet as a product, which can be listed separately.

**Comment by evaryont** [comment]
Yeah, the Jitsi website doesn't do a great job of describing the status of the desktop client, and it's been marketed for so long as "the Jitsi client" with no mention of it's inherent design. Now that it's been effectively abandoned, it should be marked as such.

Your approach sounds reasonable, to me.

**Comment by Echolon** [comment]
Tracking issue: Mark client as dead #172

**Comment by Echolon** [comment]
Close?
@bascht

**Comment by bascht** [comment]
@Echolon Yip, closing this one. There are still two review comments in #173 – so that one is still open.
