### ISSUE TITLE
Chatty is Librem Chat?

### ISSUE THREAD

**Issue by wrooot** [bascht/omemo-top#167]
There is a listing for Chatty (Purism OS). I think it is now called Librem Chat. Also OS would be PureOS, as Purism is a company. What do you think? We can still leave a link to the blog post that calls is Chatty as a historic link.

**Comment by Echolon** [comment]
Source please?

**Comment by wrooot** [comment]
Well, i have no real proof. I just assumed this by looking at their home page at https://puri.sm/ There is no mention of Chatty, but all their apps have Librem prefix, so i thought this is an official name of a prototype Chatty.

**Comment by Echolon** [comment]
Ok, let's wait if they announce more details regarding XMPP

**Comment by wrooot** [comment]
I have tried to run/install PureOS in VirtualBox VM, but it hangs on me all the time. So i guess we should wait for someone to confirm.

**Comment by bascht** [comment]
At any rate – I wouldn't list PureOS as anything else but "Linux". :-)

**Comment by Echolon** [comment]
https://github.com/bascht/omemo-top/pull/176/files

Will close this, ok?

**Comment by bascht** [comment]
@Echolon d'accord. :+1:
