### ISSUE TITLE
Does Xabber Web belongs to the list?

### ISSUE THREAD

**Issue by wrooot** [bascht/omemo-top#168]
I think the list is for the clients, not for the services. Am i wrong? Because one would also list some other services providing XMPP web chat. I don't see an option to download, install or embedd Xabber Web as Converse.js or Candy. I think it should be removed.

**Comment by Echolon** [comment]
Can you login to Xabber Web with your XMPP address?

**Comment by wrooot** [comment]
Yes, i can. But i you can only use it on their website. And given their general stance on OMEMO i'm not sure it is worth listing it. Unless they release it as a downloadable package.

**Comment by evaryont** [comment]
You can download it, it's licensed AGPL-3.0: https://github.com/redsolution/xabber-web

**Comment by wrooot** [comment]
Huh, they do not provide a link to this repo on their site. Anyway, will close this.
