### ISSUE TITLE
New Design required

### ISSUE THREAD

**Issue by ReneVolution** [bascht/omemo-top#17]
While the current design is super awesome, we think we need something more polished here :)
Please feel free to send your thoughts (a.k.a Wireframes and/or Pull Requests).

The following requirements should be met:

- [x] Use Jekyll Theming
- [ ] Responsive Design
- [x] Keep all current info
- [x] Make it beautiful ( this includes keeping the clownfish OMEMO logo)

**Comment by bascht** [comment]
Adding 1 little thing: I'd like to display the actual _progress_ of the implementation. So it'd be great to have e.g. coloured backgrounds for the table or complete progress bars per client.

**Comment by bascht** [comment]
@ReneVolution You be the judge if that last bullet point can also be considered *done*. :smile:

**Comment by ReneVolution** [comment]
Yep. Very beautiful. 😄 Awesome work. 👍

**Comment by bascht** [comment]
@ReneVolution thanks! :bowtie:

**Comment by bascht** [comment]
@ReneVolution Given that it currently _kind of works_ on mobile devices, can we close this issue? :)

**Comment by ReneVolution** [comment]
Totally missed your comment here. Sure, we can close it.
