### ISSUE TITLE
Make work in progress text more clear

### ISSUE THREAD

**Issue by wrooot** [bascht/omemo-top#184]
Currently when OMEMO support is still in progress it shows a bookmark icon. The hover text says "Client is working on OMEMO support". First, client itself can't work on something. This is done by people, developers, so semantically this is not right, in my opinion. This is even more confusing to not native English speakers (as i understood from a recent chat on Spark support forum). They read this like "Client is working with OMEMO support". They don't get the nuance of "on". They see "Client is working" and the quickly conclude, that it should work. So, i would suggest changing that to something like "Developers working to support OMEMO". Yeah, this still can be confusing, but maybe a bit more clear and correct. Maybe something like "No support for OMEMO yet" would be even more clear. Maybe also changing the icon to some tools or construction sign ("under construction") also makes sense.

**Comment by evaryont** [comment]
Ah, when I crafted those messages I hadn't considered a non-native speaker's perspective well enough. I agree, given you seeing that conversation, the wording can be improved.

For reference, here are the 3 English phrases used right now:

* When the client data is set to 100%, `OMEMO is fully supported`
* When the client data marks that the upstream developers will not support OMEMO, `Client will not support OMEMO`
* When the client is making efforts towards support, `Client is working on OMEMO support`
* There isn't a title/phrase for when there is no tracking issue. Should there be?

I think we may need to revisit the 100% message as well. There is some amount of contention around what being 100% fully means, especially around group messaging protocol support. (See MIX and OMEMO over MUC work, etc.)

The emoji were borrowed from earlier revisions. I'd prefer to keep using emoji, as I like the plain text aspect of it. If that's alright, we can change it to another emoji character very easily. Or if a specific image is desired/expected to improve understanding, that's not hard at all either.

**Comment by wrooot** [comment]
If 100% not always mean 100% then maybe just drop the word "fully".

I also think that emoji can stay, just for those that are working on support it could be replaced with something more fitting like🛠️ or 🚧

**Comment by Echolon** [comment]
Hi @wrooot,

we see that, too. But at the moment we lack on resources to implement it.

Are you interested in creating a pull request?

**Comment by Echolon** [comment]
related: 

**Replace progress bar with feature list** #122

**Comment by wrooot** [comment]
So, in https://github.com/bascht/omemo-top/blob/master/_includes/client_row.html

Change "OMEMO is fully supported" to "OMEMO is supported"
Change "Client is working on OMEMO support" to "Developer working to support OMEMO"

I'm hesitant with the icon. Which icon is best, what about licensing? I think i used emoji from my phone in the comment above. Not sure if this is alright.

**Comment by Echolon** [comment]
@wrooot 
One day @bascht said he was using those emojis https://emojipedia.org/apple/ios-9.3/pause-button/
I think then it should be fine!

**Comment by wrooot** [comment]
Submitted https://github.com/bascht/omemo-top/pull/202. Used wrench icon.
