### ISSUE TITLE
new url for profanity

### ISSUE THREAD

**Issue by trashcan55** [bascht/omemo-top#185]
http://profanity.im seems to be abandoned

current website is 
https://profanity-im.github.io/

(edit: i tried doing a pull request myself but didn't quite work out, still have to figure out git...)

**Comment by Echolon** [comment]
@trashcan55 if it is easier for you, just do it via the website. It's not that hard. Try yourself, otherwise I can help you

**Comment by trashcan55** [comment]
must have overseen this. thanks for motivating my first PR :)
