### ISSUE TITLE
ChatSecure is working

### ISSUE THREAD

**Issue by RIS2000** [bascht/omemo-top#188]
ChatSecure is 100% working OMEMO

**Comment by Echolon** [comment]
Yes for one to one chat. PR is welcome.

**Comment by butyoutried** [comment]
IMHO, we should close this issue. Current "status: 67" is perfectly reasonable, while ChatSecure [doesn't support](https://github.com/ChatSecure/ChatSecure-iOS/issues/580) OMEMO in group chats, [has issues](https://github.com/ChatSecure/ChatSecure-iOS/issues/810) with encrypted file sharing and [plenty other](https://github.com/ChatSecure/ChatSecure-iOS/search?q=OMEMO&state=open&type=issues) old OMEMO-related problems.

**Comment by bascht** [comment]
I'm with @butyoutried on this issue. It [looks like the ChatSecure project](https://github.com/ChatSecure/ChatSecure-iOS/graphs/contributors) is pretty asleep atm.
