### ISSUE TITLE
What does "100%" mean?

### ISSUE THREAD

**Issue by nogweii** [bascht/omemo-top#189]
We're are still seeing confusion/conversations around wether a given client actually does support 100% of the OMEMO spec. I think it would be worthwhile to define what that means, and to include that information in the website too.

**Comment by Echolon** [comment]
@nogweii Yes you are right. 100% is not equal to the specs. That is a problem. However, we used to keep track for at least 1:1 chat.

**Comment by Echolon** [comment]
@nogweii I will close this with referencing to this previous issue:

**Make work in progress text more clear** #184
