### ISSUE TITLE
Blabber is listed as iOS but its not avalable yet

### ISSUE THREAD

**Issue by wakest** [bascht/omemo-top#195]
https://blabber.im/en/download/ lists the iOS version at being 5% done

**Comment by Echolon** [comment]
@wakest may you PR to change this back. Yes you are right. I think we should also take it down as the project is not active at the moment.

**Comment by butyoutried** [comment]
@bascht I think this issue can be closed because that blabber.yml was already [deleted](https://github.com/bascht/omemo-top/commit/abefb971a7b47cd4e466fe565f0f65e1e4f93bdf). Currently blabber.im listed as Android-only.

**Comment by Echolon** [comment]
Thanks
