### ISSUE TITLE
Tinode

### ISSUE THREAD

**Issue by InfoLibre** [bascht/omemo-top#203]
Hello,

I found Tinode (tchat application) that seems to use OMEMO : https://github.com/tinode/chat/

**Comment by licaon-kter** [comment]
Close this, read better, just word spamming.

**Comment by InfoLibre** [comment]
?????

**Comment by licaon-kter** [comment]
@InfoLibre they're spamming Github tags
https://github.com/tinode/chat/issues/519

**Comment by InfoLibre** [comment]
Indeed, I read too quickly.

**Comment by licaon-kter** [comment]
Close this

**Comment by InfoLibre** [comment]
Done.
