### ISSUE TITLE
Sort the list

### ISSUE THREAD

**Issue by LeSpocky** [bascht/omemo-top#21]
The list seems to be completely unsorted. Sort it by any obvious or intuitive criteria like:

- alphabet
- ticket status
- …

**Comment by bascht** [comment]
Point taken! :smile: 
I also thought about adding a small JS based sorter. Kind of like https://github.com/alfajango/jquery-dynatable.
See also #17

**Comment by ReneVolution** [comment]
Agree with @bascht on this. 
We should take this into account when tackling #17.

**Comment by bascht** [comment]
Here we go.
@LeSpocky WDYT? :smile_cat:

**Comment by LeSpocky** [comment]
Really like it. :-)
