### ISSUE TITLE
Please include client Emacs jabber.el

### ISSUE THREAD

**Issue by gnusupport** [bascht/omemo-top#212]
Please include the client jabber.el as it is Emacs package that works well. But it needs OMEMO support. I would like to pay some money when somebody is willing to help on it.

**Comment by Echolon** [comment]
@gnusupport  would you like to try to PR this change?

**Comment by gnusupport** [comment]
Help me with understanding. Did maybe somebody finish OMEMO for Jabber.el?

**Comment by Echolon** [comment]
@gnusupport I just suggested that you can add the information by yourself. It is not hard. Then Emacs is listed

**Comment by gnusupport** [comment]
I agree you wish to help, but not that it is waste of time. If you are webmaster, until now you could already add the link. Otherwise, you made it for you very difficult to change a website. For me that is hard to understand. I have made multiple website revision and publishing systems, adding link is a breeze, way faster than writing your shortest comment on this issue.

http://emacs-jabber.sourceforge.net/

**Comment by gnusupport** [comment]
> @gnusupport I just suggested that you can add the information by yourself. It is not hard. Then Emacs is listed

I realized I was being ignorant, let me do it

**Comment by gnusupport** [comment]
Finished with pull request, maybe author will include it.
