### ISSUE TITLE
List Psi/Psi+ OMEMO support as incomplete due to lack of HTTP Upload encryption

### ISSUE THREAD

**Issue by ddvarpdd** [bascht/omemo-top#257]
It did work when httpupload was still an optional plugin (https://github.com/psi-im/plugins/commit/da3a0dd5160a8e315929045277e6c01463c9955c), however, it's been two years since it was moved to program core, breaking its compatibility with OMEMO plugin, and it hasn't been fixed since (https://github.com/psi-im/plugins/issues/53, https://github.com/psi-im/plugins/issues/84).

**Comment by Neustradamus** [comment]
Other historical OMEMO problems of Psi/Psi+ are here:
- https://github.com/psi-im/plugins/issues/49
- https://github.com/psi-im/plugins/issues/96
- https://github.com/psi-im/plugins/issues/114

Maybe you can update it?

@stigger, the original OMEMO developer of Psi/Psi+ know the tickets, I have relaunched today after a recent talk with Psi/Psi+ project leader @Ri0n who has confirmed me.
