### ISSUE TITLE
Bountysource images and links are dead

### ISSUE THREAD

**Issue by WhyNotHugo** [bascht/omemo-top#273]
Links suchs as https://www.bountysource.com/issues/44025760 redirect to https://app.bountysource.com/issues/44025760

But it looks like app.bountysource.com no longer resolves properly (it's a CNAME to a domain which does not exist).

[Wikipedia states](https://en.wikipedia.org/wiki/Bountysource):

> As of June 2023, Bountysource appears to have stopped paying bounties to developers with verified claims. The Blockchain Group also appears to have stopped responding to Bountysource users.[[11]](https://en.wikipedia.org/wiki/Bountysource#cite_note-11)[[12]](https://en.wikipedia.org/wiki/Bountysource#cite_note-12)

I think that the service is dead and the link ought to be removed.

**Comment by WhyNotHugo** [comment]
Please do check [the second reference there](https://github.com/bountysource/core/issues/1586): it looks like bountysource is insolvent and not paying out at all, so it's best to remove references to them entirely.

**Comment by bascht** [comment]
@WhyNotHugo Oh no, this sounds bad. Thanks for bringing this to my attention. I should've yeeted them on reading the word "Blockhain Group" :sob:.

**Comment by bascht** [comment]
@WhyNotHugo site is redeployed, all Bountysource links are gone.
