### ISSUE TITLE
Add Thunderbird to the list

### ISSUE THREAD

**Issue by allo-** [bascht/omemo-top#31]
Thunderbird has a libpurple chatclient. I am not sure how to use libpurple plugins there, but i opened an issue at the lurch repo as well.

**Comment by bascht** [comment]
I've lost track of Thunderbird. The integrated client has nothing to do with [Instantbird](http://instantbird.com/), no?

**Comment by EmPeWe** [comment]
It's misnamed Chat Core, see #47. Instantbird uses libpurple (see http://www.instantbird.com/faq.html#license), but I don't know, if Chat Core is based on libpurple or is mozilla's own work.

**Comment by azrdev** [comment]
Thunderbird was added in 76ff404d07c7856c1e9f35f4aa44291593e80930, this can be closed

**Comment by bascht** [comment]
Yup, @azrdev is right. It's already in the list and Instantbird looks pretty much stale / dead at this moment.
