### ISSUE TITLE
make an entry for distribution packaging?

### ISSUE THREAD

**Issue by deknos** [bascht/omemo-top#35]
Hi, would it be possible to show in your table an entry for distribution packaging? like "available in..." with debian, fedora, centos and arch (aur)?

for debian/ubuntu there is no packaging with lurch for example :)

**Comment by bascht** [comment]
I guess most distributions lack packaging for the latest plugin versions, so I think we could split this into:

* Available in the base distribution
* Available as an add-on repository

WDYT?

**Comment by deknos** [comment]
That's a good idea. Especially if there would be a link to the addon-repository! :)
I'll try the lurch-plugin for myself as well now..

**Comment by bascht** [comment]
@deknos Change #36 splits data / markdown, so now we can finally add properties without having merge conflicts all over the place. 

I think we could add simple badges and pack it all in one field:

![none](https://img.shields.io/badge/package-none-red.svg)
![third party](https://img.shields.io/badge/package-third%20party-orange.svg)
![distribution](https://img.shields.io/badge/package-distribution-green.svg)

Come to think of it: How shall we decide which Distributions matter? :grimacing:

**Comment by tdemin** [comment]
XMPP and OMEMO are not Linux-specific, so adding Linux-specific badges isn't a way to go for the site.

**Comment by bascht** [comment]
The longer I think about it, the more I'm in line with @tdemin. Listing distro specific instructions / packages source will quickly get out of hand. I guess having a single "Installation instructions" link will be sufficient.
