### ISSUE TITLE
Failed to load Tablesort

### ISSUE THREAD

**Issue by ReneVolution** [bascht/omemo-top#37]
Not sure why and if this is only temporary, but the site fails to load the Tablesort module.

<img width="693" alt="screen shot 2017-02-15 at 07 54 36" src="https://cloud.githubusercontent.com/assets/2199428/22963581/1a0755b8-f354-11e6-8c9f-6acf55dcdc49.png">

**Comment by bascht** [comment]
Hopefully this was a one-timer, but I've added some safeguards. :smil
