### ISSUE TITLE
Sort by "done" first then by "work in progress"

### ISSUE THREAD

**Issue by DreamFlasher** [bascht/omemo-top#38]
Is it possible to have the list sorted first by "done" and then by "work in progress", because it would be nice to see the finished ones first. 

Or maybe include a date of publication/latest update and sort by that? Then we could attribute conversations to being the first one :)

I would do the work it if you think it's a good idea.

**Comment by bascht** [comment]
> Is it possible to have the list sorted first by "done" and then by "work in progress", because it would be nice to see the finished ones first.

That would be nice indeed. I don't think [tablesort.js](http://tristen.ca/tablesort/demo/) supports sorting by multiple criteria. What works (manually, atm) is: Sorting them first by _wip_, then by _testing_ and then by _done_:
![screenshot_20170216_201404](https://cloud.githubusercontent.com/assets/51264/23036822/88dc3d92-f484-11e6-943c-525c87c6843c.png)

You could try to get this to work programmatically. :smile: 

> Or maybe include a date of publication/latest update and sort by that? Then we could attribute conversations to being the first one :)

I think having more metadata would be nice, but it would bloat up our table even more. (See #40).

**Comment by DreamFlasher** [comment]
Yeah, manually sorting works right now, but that's not so nice. Actually we don't need three columns, it could be replaced by just one column "status". And I think the status should be in the form "date done" or "date wip" and then we do the default sort on that.

**Comment by bascht** [comment]
Come to think of it: You're completely right! It might be hard to get accurate dates of "_Work in Progress_" or "_Testing_", but I'd like to see your idea. Want to give it a go?

**Comment by DreamFlasher** [comment]
I'm happy to give it a go :)

**Comment by bascht** [comment]
Let me know if you run into problems setting up the site locally. :smiley_cat:

**Comment by LeSpocky** [comment]
FWIW, I like the three column approach.

**Comment by DreamFlasher** [comment]
Here's the PR: https://github.com/bascht/omemo-top/pull/41/commits @bascht :)

**Comment by bascht** [comment]
@LeSpocky I think we can still keep the 3-column look (kind of like a progress bar) while still having a combined state in one field of the data file :)

**Comment by DreamFlasher** [comment]
@LeSpocky Could you elaborate what you like about the three column approach? What do you think about my proposal? Maybe something like a progressbar in the field would work?

**Comment by ReneVolution** [comment]
I have created PR #42 which would keep the design and fix the issue. What do you guys think?

**Comment by bascht** [comment]
@ReneVolution @LeSpocky @ReneVolution Can we close this issue?

**Comment by LeSpocky** [comment]
You can probably close it. https://omemo.top/ looks good for me.

**Comment by ReneVolution** [comment]
Yep 👍. Looks good for me too.
