### ISSUE TITLE
Add detailed section per client

### ISSUE THREAD

**Issue by bascht** [bascht/omemo-top#40]
I think there is way more info than we can cover at the moment (see #38). So – having a small section per client (maybe even with installation help / packaging status) below the table would be really nice.

**Comment by DreamFlasher** [comment]
Then let's add my proposal here: I think the release date would be very valuable information to add to this section.

**Comment by mimi89999** [comment]
@bascht I think there should be multiple cases like: WIP, 1:1, MUC, File shareing and every would have like 25% and based on that, you would calculate the %.

**Comment by bascht** [comment]
@mimi89999 The longer I think about the `%` the more I think we should go back to the old system of "sort by features". Having a single number is really nice (especially if it's _100%_) but it can be quite misleading like @uchchishta attested over at #70. 

### Suggestion
_(once we have detailed info per client)_

We add checkbox filters on top of the table with _say_ 5 distinct feature flags ("Experimental", "1:1", "MUC", "Encrypted File transfer") and by clicking those boxes the list of clients get's smaller and smaller (Ending up with Conversations as the only client once all boxes are ticked. 😬).

wdyt?

**Comment by mimi89999** [comment]
@bascht I think the % can stay if:
1. It is calculated based on those 5 features
2. Feature list is accessible when going over with the cursor or clicking on it

> Ending up with Conversations as the only client once all boxes are ticked.
Conversations and Gajim.

**Comment by bascht** [comment]
> Feature list is accessible when going over with the cursor or clicking on it
introduces another interaction layer. If those are just green / red / gray boxes in a row, everything is visible immediately. I'm not emotionally attached to the percentage. :grimacing:

**Comment by uchchishta** [comment]
Can you put a `💯` next to a client if it supports all the three if you go with the filterable table?
Also `n/a` if a client doesn't do a thing at all

**Comment by bascht** [comment]
@uchchishta I think that wouldn't even be necessary if we have columns for all features, no?

**Comment by ReneVolution** [comment]
Heyo, I have started to work on this. To find out if this kindof matches your expectations, please check the PR #85.

**Comment by lstrtstr** [comment]
> +features:
> +  single_chat: true
> +  group_chat: true
> +  encrypted_files: true

Thanks!
Two more features that should be listed, IMO, are Message Carbons and Message Archive Management. These seem to be important features for "full functionality" to many people.

**Comment by lstrtstr** [comment]
Oh, and probably not only "true" and "false," but also "via plugin" would make a lot of sense.

**Comment by DreamFlasher** [comment]
I think true/false is sufficient, if supported by a plug-in it's supported no need to overcomplicate things. 
Yet, I still believe the release date should be included in the client information.

**Comment by bascht** [comment]
Sorry for the radio silence in the last few months. I'll try to get this back on track in February. 😺

**Comment by bascht** [comment]
@lstrtstr Yes. I want to keep the maintenance effort for omemo.top at a manageable level. Wikipedia / etc. might be a better place for this, think e.g. https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_clients#XMPP-related_features
