### ISSUE TITLE
XMPP Client from SailfishOS

### ISSUE THREAD

**Issue by thoys1** [bascht/omemo-top#52]
Hei, SailfishOS is nice, but the native xmpp client has no omemo encryption. 
Can you please add it to your list?

**Comment by bascht** [comment]
@thoys1 Hi there. Do you know if there is a proper website I could link to? I only found https://sailfishos.org/wiki/Messaging

That aside, it looks like [Shmoose](https://github.com/geobra/harbour-shmoose) is another Sailfish OS based XMPP client that has OMEMO on it's target list :)

**Comment by zarelit** [comment]
@bascht that wiki is official and the [IM paragraph](https://sailfishos.org/wiki/Messaging#IM) actually contains the link to the backend repo. The whole messaging application is comprised of several repos you can find at [mer-core gitlab](https://git.merproject.org/mer-core).
I suppose OMEMO won't be implemented in the UI until it's implemented upstream in telepathy so the same issue of Empathy can be used.

Schmoose is indeed a native XMPP application and should be a separate entry

**Comment by bascht** [comment]
@zarelit Are you using a Jolla device as your daily driver?

**Comment by zarelit** [comment]
@bascht  I used to but not anymore because of an hardware issue. I'm close to someone that use it everyday and somehow follow the development (e.g. by reading the release notes). Unluckily no news on this side in the recent SFOS3

**Comment by bascht** [comment]
@zarelit Ok, interesting. Same here – only following the development but I guess it's too risky to go all-in on that platform as my primary phone. :grimacing:
