### ISSUE TITLE
Update Miranda NG status

### ISSUE THREAD

**Issue by Kagami** [bascht/omemo-top#53]
Seems like they have some progress on OMEMO:
https://github.com/miranda-ng/miranda-ng/commits/master/protocols/JabberG/src/jabber_omemo.cpp

**Comment by bascht** [comment]
@Kagami Thanks for he find! :+1: Looks like they're making real progress here. :sparkles:

**Comment by Kagami** [comment]
Thanks. Seems like need to bump `status` to some value too?

**Comment by bascht** [comment]
Yip, you're completely right. I need to clean this up a bit. I think this is related to #38

**Comment by RIS2000** [comment]
Miranda NG still have no working OMEMO!
