### ISSUE TITLE
"tracking issue" links overlap

### ISSUE THREAD

**Issue by oodbur** [bascht/omemo-top#54]
the "tracking issue" icon link areas overlap well into the icons of the preceeding clients.
clicking the linked "tracking issue" icon may lead you to the page for the client listed below if you hit near the lower end of the icon.
![link problem](https://cloud.githubusercontent.com/assets/16760311/24953551/3c12bb32-1f6b-11e7-9b0b-f65a36e28a4b.png)

**Comment by bascht** [comment]
@oodbur Thanks for the report! Which Browser / Browser Version / OS is that?

**Comment by oodbur** [comment]
some flavor of Firefox 45

**Comment by oodbur** [comment]
might be a browser bug.
it shows up in Tor Browser (v6.5.x), not in vanilla Firefox.

**Comment by bascht** [comment]
I tried to reproduce it with Tor Browser 6.5.2 – still looking good:

![screenshot from 2017-04-24 09-15-46](https://cloud.githubusercontent.com/assets/51264/25326042/a014328e-28ce-11e7-93b9-28c1c2b8fcac.png)

Could you check the developer console for errors / warnings?

**Comment by oodbur** [comment]
i'm talking about the click-sensitive linked areas around the individual tracking issue stars. those are invisible in your screenshot. my screenshot contains a selection (mousedown - drag) that makes that area visible.

**Comment by bascht** [comment]
@oodbur Give it another try (you might have to hard-flush your cache to get a fresh css file from Cloudflare)

**Comment by bascht** [comment]
![screenshot_20170503_092557](https://cloud.githubusercontent.com/assets/51264/25651282/879620ee-2fe2-11e7-9fb6-3b22ce330ec0.png)
Still looks a bit off in Tor Browser, but at least it's usable and it doesn't break other browsers.
