### ISSUE TITLE
why is PRISM-break on the list?

### ISSUE THREAD

**Issue by vanitasvitae** [bascht/omemo-top#62]
PRISM break is a list of free open source alternatives to proprietary software. Its not an XMPP client and therefore it is not able to do OMEMO encryption.

**Comment by vanitasvitae** [comment]
Please review #63, which resolves this issue.

**Comment by bascht** [comment]
@vanitasvitae Good find. I'm pretty sure it got on our list because it has a GitHub Repo / Issue / Bounty on it's name. It also tracks which clients support OMEMO yet: https://prism-break.org/en/protocols/omemo/ – but nevertheless, it's not a client and is probably misleading.

**Comment by vanitasvitae** [comment]
Hi! No problem :)
Could you add an extra category for libraries with OMEMO support? There are smack-omemo *cough* and libomemo, which could be listed there :)

**Comment by bascht** [comment]
@vanitasvitae Issue is fixed via 8157fc8.
And nope, I won't start adding libraries. I want `omemo.top` to be a user facing site. :smiley:

**Comment by vanitasvitae** [comment]
Okay, I understand that :)
