### ISSUE TITLE
Add Lurch4Adium

### ISSUE THREAD

**Issue by shtrom** [bascht/omemo-top#65]
Hey there,

I have just finished a first version, apparently working, of an Xtra for Adium, https://github.com/shtrom/Lurch4Adium.

From my rudimentary tests, it works as it should, so I guess this should address the Adium case.

**Comment by bascht** [comment]
Whoa, nice! I never would have guessed that Adium would still get any kind of support. :grimacing: 
Can you submit a Pull Request with the changes? (I think setting Adium to "testing" / 30-50% would be appropriate)

**Comment by shtrom** [comment]
On Fri 09 Jun 2017 at 02:18:28 -0700, Sebastian Schulze wrote:
> Whoa, nice! I never would have guessed that Adium would still get any kind of support. :grimacing: 
> Can you submit a Pull Request with the changes? (I think setting Adium to "testing" / 30-50% would be appropriate)

Well, that's the only usable Jabber client I could find on OS X.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by bascht** [comment]
Ýup, I know. Currently the only thing I could recommend macOS friends was to stay away from Adium / an unpatched libotr. ;)

**Comment by bascht** [comment]
Fixed via #66
