### ISSUE TITLE
What about Pix-Art? (Conversations Fork)

### ISSUE THREAD

**Issue by Echolon** [bascht/omemo-top#69]
Hi,

what about listing this fork of Conversations? 

https://github.com/kriztan/Pix-Art-Messenger/releases
https://jabber.pix-art.de/

Unfortunately, it is only available in German at the moment. But this could be mentioned, or?

Cheers

**Comment by bascht** [comment]
Sure. I didn't know about this fork yet. They seem to have just copied the complete repo. Is there a list of distinct features?

**Comment by Echolon** [comment]
Hi, yes in general the developer just copied the app and merges new updates. But he made a few changes. His focus was to make conversations easier for non-technically talented people. So he decrease to availability of options, made some interface adjustments, set some settings to always on (e.g. Foreground service) and I think the standard server for new registrations is his server (to keep it simple). Furthermore, he put all additional conversation add-ons into the app. As I understood there shall be further improvements in the future, hopefully more languages supported.

The changelog: https://raw.githubusercontent.com/kriztan/Pix-Art-Messenger/master/CHANGELOG.md

**Comment by bascht** [comment]
Looks interesting. Thanks for the heads-up! Can you send a PR?

**Comment by Echolon** [comment]
Sorry, I'm not real programmer. I don't know how to do this - or let's say I don't have the time to get into this right now :(
I just intended to suggest it.

**Comment by bascht** [comment]
Closed via #71

**Comment by Echolon** [comment]
Correction: It's available in at least German and English
