### ISSUE TITLE
ChatSecure is not 100%

### ISSUE THREAD

**Issue by mimi89999** [bascht/omemo-top#70]
ChatSecure doesn't support OMEMO in MUC: https://github.com/ChatSecure/ChatSecure-iOS/issues/580 and has issues with OMEMO file transfer (it is not working): https://github.com/ChatSecure/ChatSecure-iOS/issues/810

**Comment by bascht** [comment]
:thinking: I see your point, but I think those MUC + file transfer are more of an _add-on_ to the experience. I try to keep the actual overview simple and try to symbolise »E2E encrypted chat via OMEMO works« as 100%. 

A more detailed feature comparison would be something for #40. wdyt? :smile:

**Comment by mimi89999** [comment]
For me 100% is *everything works fine*, *the full experience is good*. For me group chat and file sharing are normal (everyday) usage and not an add-on...

I think #40 might be a solution... How is the % calculated now?

**Comment by bascht** [comment]
The percentage isn't calculated. It used to be three columns and we merged into one with #42. :wink: 

The problem with _the full experience is good_ is: It's **your** experience. If you only use 1:1 chats with Conversations + ChatSecure, then your overall experience will be _100%, everything works fine_.

**Comment by uchchishta** [comment]
who only uses 1:1? People generally think 100% means it has e2e  support for all the chats, including group and uploads. You have not even mentioned this anywhere.
You should also think about **others**.
This is outright misleading.

**Comment by Pentabyteman** [comment]
It would be great if the next update could include OMEMO MUC. I'm not too keen about inline pics, but with ChatSecure you should be able to chat securely, also in group chat.

**Comment by bascht** [comment]
@uchchishta The fact that you're the first one to bring up MUC is proving my point. :smiley_cat:
It's highly subjective, but I'm happy to talk about any improvement suggestions that will fit into the visual space we have.

**Comment by mimi89999** [comment]
@bascht Could you comment on my proposition: https://github.com/bascht/omemo-top/issues/40#issuecomment-323594052 ?

**Comment by bascht** [comment]
@mimi89999 Ah, yip – sorry. Only saw one email thread.

**Comment by mimi89999** [comment]
@bascht Can I downgrade ChatSecure to 67%?

**Comment by bascht** [comment]
@mimi89999 ChatSecure + Pidgin, no?

**Comment by tdemin** [comment]
> The fact that you're the first one to bring up MUC is proving my point. 

@bascht it doesn't. The only reason he's the first to bring MUC up is that the site isn't very popular, and only few of the users might actually send issues.

**Comment by uchchishta** [comment]
Also I'm not the first, it was @mimi89999 ☺

**Comment by albjeremias** [comment]
why is this not on the list? is there a resume?

**Comment by gerg5c42g542g2c54g52c** [comment]
So it seems Zom is 100% OMEMO now and ChatSecure is still not 100% and there was me thinking Zomo is a fork of ChatSecure following its development. Am I wrong? Can someone explain this?

**Comment by sirdrakeistda** [comment]
> So it seems Zom is 100% OMEMO now and ChatSecure is still not 100% and there was me thinking Zomo is a fork of ChatSecure following its development. Am I wrong? Can someone explain this?
Zom is not a XMPP Client anymore. It switched to Matrix as protocoll. I don't understand this percentage anyway. OMEMO encrypted file transfer is not possible in Monal, but Monal has 100%.
