### ISSUE TITLE
Add kandru to the list

### ISSUE THREAD

**Issue by allo-** [bascht/omemo-top#89]
kandru is a conversations fork and probably supports omemo or will do so soon.

**Comment by evaryont** [comment]
Do you have a link to the fork?

**Comment by allo-** [comment]
https://github.com/Kandru/kandruIM

Seems to follow Conversations upstream closely and have working OMEMO since some time.

**Comment by bascht** [comment]
Pinging @derkalle4 – the `master` looks a bit stale and already lags > 2 months behind Conversations master. Is the project still active? 😺

**Comment by derkalle4** [comment]
@bascht project still alive and yes atm it follows the conversations upstream closely because conversations has integrated the things I wanted to have in a messenger. But I'll spend some time to keep it in sync with Conversations if needed ;)

**Comment by bascht** [comment]
@derkalle4 Thanks for the heads-up. 😄 Is there a mission statement / list of features that makes Kandru stand out in contrast to Conversations?

**Comment by Echolon** [comment]
@derkalle4 now your website isn't accessible anymore. I will close this.
If there is development, please directly make a PR and we add it to the list.
