### ISSUE TITLE
Psi+ OMEMO bounty

### ISSUE THREAD

**Issue by ValdikSS** [bascht/omemo-top#91]
Hello, I offer bounty for OMEMO support for Psi+, but not on bountysource. Please add that to the list.
https://github.com/psi-im/plugins/issues/10#issuecomment-357455647
https://github.com/psi-plus/main/issues/673#issuecomment-357449812

**Comment by bascht** [comment]
@ValdikSS Wow, that's a huge bounty. 💰  Is there a bountysource Link that we could link to? Currently I only see the comments and we only link to `bountysource.com` (https://github.com/bascht/omemo-top/blame/master/index.md#L35). Otherwise we could rework the code a bit.

**Comment by ValdikSS** [comment]
I think this issue is not actual anymore, since @stigger is already implementing OMEMO and there's working prototype already.
I won't close it for now and update it as soon as Psi+ gets OMEMO support.

**Comment by Neustradamus** [comment]
Thanks @ValdikSS for the lighting and thanks @stigger for seeing it even though his work had been started before :)

**Comment by bascht** [comment]
@ValdikSS So… …can this issue be closed?

**Comment by ValdikSS** [comment]
Not really yet. OMEMO plugin is not yet fully stable, and @stigger hasn't contacted me yet.

**Comment by bascht** [comment]
Oh, alright – but if it is "in progress" you can close this issue and just submit a new PR once OMEMO support in Psi+ is stable.

**Comment by Echolon** [comment]
@ValdikSS push

**Comment by Neustradamus** [comment]
For all people, have you updated your Psi/Psi+?

I would like feedbacks from all users for OMEMO:
- Between Psi, Psi+, and other OMEMO XMPP clients
- OMEMO detection (grey icon / color icon)
- Secure chat (1:1)
- Secure mucroom
- New fingerprints detection
- OMEMO option possibilities (Options->Plugins->OMEMO options), all are good?
-- "Clear devices" and "Refresh" buttons in "Manage Devices" are missing (https://github.com/psi-im/plugins/issues/38)
-- Impossible to remove fingerprints of contacts (https://github.com/psi-im/plugins/issues/37)
-- Regenerate "Own fingerprint" is missing (https://github.com/psi-im/plugins/issues/36)

In the same time:
- OTR feedback too
- GnuPG feedback too

Thanks in advance.

**Comment by ValdikSS** [comment]
OMEMO support in Psi+ has been implemented in full.

**Comment by Neustradamus** [comment]
@ValdikSS: It works but not without bugs, we need more tickets for inform @stigger about problems.
Your commit has a mistake: https://github.com/bascht/omemo-top/commit/b948ae4fef28b3516b4c98a5291cd22854f14709

**Comment by Neustradamus** [comment]
@ValdikSS, @bascht, @butyoutried: Current historical OMEMO problems of Psi/Psi+ are here:
- https://github.com/psi-im/plugins/issues/49
- https://github.com/psi-im/plugins/issues/96
- https://github.com/psi-im/plugins/issues/114
- https://github.com/psi-im/plugins/issues/121
- https://github.com/search?q=org%3Apsi-im+omemo&type=issues

Maybe you can update it?

@stigger, the original OMEMO developer of Psi/Psi+ knows the tickets, I have relaunched today after a recent talk with Psi/Psi+ project leader @Ri0n who has confirmed me.

**Comment by ValdikSS** [comment]
@Neustradamus, do you want to update it in the list? If you're referring to the code, there's little I can do.

**Comment by Neustradamus** [comment]
Yes, it must be added in the list.

If you can help to solve the specified problems, it will be nice.

Thanks in advance.
