### ISSUE TITLE
Why is Conversations (Android) a crying emoji?

### ISSUE THREAD

**Issue by xgpt** [bascht/omemo-top#96]
It appears as though it has appropriate OMEMO support. I am not a technical user, but it would appear that this is out of date.

**Comment by bascht** [comment]
@xgpt good catch. This is an issue with the way I decided to represent the "tracking issue". For any other client it means: They don't even track / decide to implement the OMEMO support. Conversations had OMEMO support from the start on as far as I remember. It should get a distinct, different emoji. 😸

**Comment by Echolon** [comment]
Yes, agreed. I think a nice green tick would do it for all clients which are done.
Makes choice for people more intuitive.

**Comment by bascht** [comment]
@evaryont sounds great, do you want to go ahead and submit a PR? I've taken the liberty to merge #40 as I don't want to keep rebasing this PR upon every change. :grimacing:

**Comment by evaryont** [comment]
Ah, this had gotten lost my pile of TODO items. I can send one in soon,
I'll make sure it's based off the latest HEAD.

**Comment by bascht** [comment]
And #103 is merged. Thanks to @evaryont!

**Comment by bascht** [comment]
I opened #104 to add some HTML labels to the Emojis, just for clarification.
